### ISSUE TITLE
INU correction gone wrong

### ISSUE THREAD

**Issue by oesteban** [nipreps/smriprep#125]
![ds005-sub-08-biasfield](https://user-images.githubusercontent.com/598470/67033660-1aca3e80-f0cb-11e9-9842-8b920538c700.png)

fmriprep-1.5.1rc1 - ds005/sub-08

**Comment by oesteban** [comment]
ds051/sub-06

![ds051-sub-06-biasfield](https://user-images.githubusercontent.com/598470/67034364-68937680-f0cc-11e9-9603-91c7a53d49f9.png)

**Comment by oesteban** [comment]
Possibly duplicate of #127

**Comment by oesteban** [comment]
At least for the first case, the problem stems from a poor Atropos segmentation (ref. #109, as we will need to check Atropos' segmentation before forwarding it).

WM (necessary for the subsequent N4 step) is label 3 (the red spots):

<img width="381" alt="Screen Shot 2020-05-08 at 1 39 14 PM" src="https://user-images.githubusercontent.com/598470/81447471-86d8c680-9131-11ea-973b-7d0a5f60deb1.png">

**Comment by oesteban** [comment]
Because this one will rely on nipreps/niworkflows#506, I'm not marking this as a bugfix to the maintenance of old series.

**Comment by oesteban** [comment]
For ds005/sub-08, this revision of the workflow actually made ATROPOS work better, and find a decent segmentation.

ds051/sub-06 is a case with hyper-intense vessels that still confuse ATROPOS (even with the better INU correction). However, with the multiplication of the WM posterior from ATROPOS with the WM prior from the template, the INU correction is not so horrible after all:

![Screen Shot 2020-09-17 at 6 54 55 PM](https://user-images.githubusercontent.com/598470/93503066-e03ed680-f917-11ea-8b9c-b028abef42c0.png)

left is the segmentation from ATROPOS showing how it picks only the brightest spots as WM (white color), right is the weights image for N4 (i.e., product of the WM posterior and the WM prior) and middle is the final, INU-corrected image.

**Comment by oesteban** [comment]
This is to say that I would keep working on PR to get it to work on ds005/sub-08 (meaning, the ATROPOS segmentation should not look like above - https://github.com/nipreps/smriprep/issues/125#issuecomment-626011343), and then address ds051/sub-06 on a different PR, including the idea of estimating the overlap of the different posteriors from ATROPOS and the WM prior from the template

**Comment by oesteban** [comment]
Sorry for the multiple posting - the reportlet from ds051/sub-06 just came out:

![Screen Shot 2020-09-17 at 7 05 27 PM](https://user-images.githubusercontent.com/598470/93503828-ea150980-f918-11ea-8844-fbd2fab72a56.png)

It indeed seems fixed (although the ATROPOS refinement did not).

Please let me know if you agree with the proposed plan:

1 - finish this PR (address comments, test on more data, etc.)
2 - iterate to improve the ATROPOS refinement.

**Comment by mgxd** [comment]
a definite improvement, though not the best brain mask. plan sounds good to me 👍
