### ISSUE TITLE
Transferring to nipreps organization

### ISSUE THREAD

**Issue by oesteban** [nipreps/smriprep#168]
After experiencing how easy it has been transferring SDCFlows, should I go for this one?

**Comment by effigies** [comment]
Same as https://github.com/poldracklab/niworkflows/issues/462#issuecomment-586537021:

> I vote for waiting until after the 20.0.0 release. No need to fiddle with the process between now and then.

**Comment by oesteban** [comment]
Postponed to right after 20.2

**Comment by oesteban** [comment]
Okay, this is done. I have `find . -type f -exec sed -i 's+poldracklab/smriprep+nipreps/smriprep+g' {} \;` on `master`, but I don't know whether we should backport this kind of changes to actively maintained branches. Please open issues if some further changes related to this move are necessary.
