### ISSUE TITLE
FreeSurfer 7

### ISSUE THREAD

**Issue by effigies** [nipreps/smriprep#184]
FreeSurfer 7 has been [released](https://surfer.nmr.mgh.harvard.edu/fswiki/ReleaseNotes).

Post-LTS would be a good time to start seeing what accommodations need to be made.

TODO:

* [x] Update nipype recon-all interface to handle any changes to the expected outputs per-stage
* [x] Check the coarse parallelization workflow for validity
* [x] Validate downstream usage of FreeSurfer products is still valid, e.g., CRAS adjustments to GIFTI coordinates, mri_vol2surf invocations, etc.

**Comment by oesteban** [comment]
> Bias field correction with ANTS N4 instead of MNI N3 (removes dependency on MINC software)
> ANTS denoise is used when creating the orig surface (but not thefinal surfaces)

Both Interesting!
