### ISSUE TITLE
Option to remove "-it" from docker command, to avoid TTY error in non-interactive shell?

### ISSUE THREAD

**Issue by kjamison** [nipreps/smriprep#209]
I'm running smriprep-docker in a google cloud environment using automatic startup scripts, and found that it was exiting with the error "The input device is not a TTY".  If I have my startup script explicitly pull poldracklab/smriprep:0.6.1 and then run the "docker run" command smriprep-docker was trying to execute, but without the "-it", it all works fine. 

I like the flexibility of the wrapper, so it would be nice to keep using it. Can you perhaps include a argument to skip the "-it" flag? Same would be useful for fmriprep-docker

**Comment by mgxd** [comment]
sounds like a good idea, @kjamison, perhaps as a `--noninteractive` or `--no-tty` flag? would you be up for submitting a PR with this new addition?
