### ISSUE TITLE
Fast-track not finding all expectations with ``--cifti-output``

### ISSUE THREAD

**Issue by oesteban** [nipreps/smriprep#211]
I believe the problem comes from the "hidden" MNI152NLin6Asym space.

**Comment by bpinsard** [comment]
If seems that if `--anat-only` was ran with `--cifti-output` or  with `--output-spaces MNI152NLin6Asym ...`  then the necessary files for anat fast-track with `--cifti-output` are present, right?

**Comment by oesteban** [comment]
I haven't actually checked myself. If you could confirm that, it would be a good step forward.

**Comment by bpinsard** [comment]
It seems to be the working.
