### ISSUE TITLE
Skullstripped set to True in metadata, but associated images aren't skull stripped

### ISSUE THREAD

**Issue by switt4** [nipreps/smriprep#236]
**Describe the bug**
For fMRIPrep versions >=1.5, the metadata in the .json sidecar for the `space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz` image files indicates that `"SkullStripped": true`.  However, the associated images files are not skull stripped.

Further adding to the confusion, for fMRIPrep versions <=1.4, the `space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz` image files were written out as skull stripped images.

Is is possible to get a flag that users can set to request that skulled stripped `space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz` image files are written out?

Thanks,
Suzanne Witt

**Exact command line executed**  
Most recent example for fMRIPrep v 20.2.0 (LTS), redacted to remove user IDs from directory and file paths.
```
/usr/local/miniconda/bin/fmriprep bids fmriprep participant --participant_label UWO035 --nthreads 8 --n_cpus 8 --mem_mb 32000 --omp-nthreads 8 --use-plugin fmriprep_multiproc_8c_32gb.yaml -w /localscratch/40638590.0 --fs-license-file /freesurfer/.license --resource-monitor --notrack --fs-no-reconall --use-syn-sdc

```

**Are you positive that the input dataset is BIDS-compliant?**
- [X] I have used the online BIDS-Validator
- [ ] I have run a local installation of the BIDS-Validator (please, note the version of the validator here).
- [X] I let *sMRIPrep* check it for me (in other words, **I didn't set the `--skip-bids-validation` argument**).
- [ ] No, I haven't checked myself AND used the `--skip-bids-validation` argument.

***sMRIPrep* feedback information**
Please attach the full log written to the standard output and the crashfile(s), if generated.

**Visual reports of *sMRIPrep***
If applicable, add screenshots or attach the corresponding "reportlets" to help explain your problem.

**Installation type (please complete the following information):**
 - [ ] "Bare-metal"
 - [X] Singularity
 - [ ] Docker

**Additional context**

**Comment by effigies** [comment]
Thanks for moving this issue over here.

We're definitely setting `SkullStripped = True` here:

https://github.com/nipreps/smriprep/blob/881fe18f005177a9d6ff1bc4a26d0d0b39cd27a9/smriprep/workflows/outputs.py#L144-L148

Thinking about this, I'm inclined to agree that there's no real use to producing a T1w image in MNI space with warped non-brain anatomy.

@bpinsard @oesteban @mgxd Question: What is the fix for this in LTS? Mark `"SkullStripped": false`? Or skull strip the NIfTI?

Or any disagreements that the file should be skullstripped in the next release it can be?

**Comment by oesteban** [comment]
> Thinking about this, I'm inclined to agree that there's no real use to producing a T1w image in MNI space with warped non-brain anatomy.

Yup, if there's a reason I honestly don't remember it.

> @bpinsard @oesteban @mgxd Question: What is the fix for this in LTS? Mark `"SkullStripped": false`? Or skull strip the NIfTI?

I guess for the LTS this should be marked `"SkullStripped": false`.

> Or any disagreements that the file should be skullstripped in the next release it can be?

None on my side.

**Comment by bpinsard** [comment]
I agree with all what have been said, fixing the json for the LTS seems to be the best fix.
I can make a PR for the next minor release.

**Comment by effigies** [comment]
It happened with the release of sMRIPrep 0.4.0, which introduced outputnodes and poutputnodes, and renamed a lot of fields, so my guess is that it was just an error in the refactoring.

> I guess for the LTS this should be marked `"SkullStripped": false`.

To check this out, I've forked a `maint/0.4.x` off from 6a556bcf16a33ea21ed4fdcb8b7335332af10654, which involved pulling in some CircleCI fixes from more recent releases. Once that's working, I'll make a string of updates into the `maint/0.5.x`, `maint/0.6.x` and `maint/0.7.x` branches. We can decide then which series need bug-fix releases.

**Comment by effigies** [comment]
Okay, looks like we're all updated. Here's the dependency table for which branches could be released:

| fMRIPrep series | sMRIPrep series |
|--|--|
| 1.5.x | 0.4.x |
| 20.0.x | 0.5.x |
| 20.1.x | 0.6.x |
| 20.2.x | 0.7.x |

TBH I'm not sure if it's worth going back past 20.2, but at least we'll be able to if there's call for it.

**Comment by effigies** [comment]
0.7.1 released and merged into `master`. Next step is to figure out how to get the skullstripped image back and reset the metadata.

**Comment by effigies** [comment]
Looks like what happened was we switched from passing the resampled data as generated by the normalization step (which is skull-stripped) to passing the original data and a set of transforms, and re-applying the resampling.

Our options are either to mask while we generate the derivatives or start piping the resampled images through again. I think it will be clearer to mask and resample and will open a PR to that effect.
