### ISSUE TITLE
question about Spatial normalization with smriprep

### ISSUE THREAD

**Issue by ali3654** [nipreps/smriprep#238]
hello experts,

If I run smriprep with a docker for a subject as without a special option then the HTML report of this brain does not say anything about spatial normalization. 

This is also not mentioned under Methods in the HTML report.

only when i run smriprep with docker again with the option --output-spaces MNI152NLin2009cAsym the HTML report of the brain shows that a spatial normalization has been performed and a picture of the spatial normalization is shown

But there are 12 nifti files when I run smriprep with --output-spaces MNI152NLin2009cAsym. that was not my goal to have so much Nifti data .

Is there really no spatial normalization when I run smriprep without the option --output-spaces MNI152NLin2009cAsym ?

**Comment by oesteban** [comment]
> Is there really no spatial normalization when I run smriprep without the option --output-spaces MNI152NLin2009cAsym ?

Correct. For the *sMRIPrep* *BIDS-App* the default is not running any spatial normalization unless they are explicitly requested with `--output-spaces`. *fMRIPrep* overrides this default behavior and *dMRIPrep* does not.

**Comment by oesteban** [comment]
> But there are 12 nifti files when I run smriprep with --output-spaces MNI152NLin2009cAsym. that was not my goal to have so much Nifti data

Can you provide a list of these files?

**Comment by ali3654** [comment]
yes ok thank you very much.
Then my question is over. 
I can still send you my output but I think the output is all right because I worked with the option --output-spaces.

My output:

"""
dataset_description.json
logs
sub-OAS30204.html
sub-OAS30204
├── figures
│   ├── sub-OAS30204_desc-about_T1w.html
│   ├── sub-OAS30204_desc-summary_T1w.html
│   ├── sub-OAS30204_ses-d0020_desc-conform_T1w.html
│   ├── sub-OAS30204_ses-d0020_dseg.svg
│   └── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_T1w.svg
└── ses-d0020
    └── anat
        ├── sub-OAS30204_ses-d0020_desc-brain_mask.json
        ├── sub-OAS30204_ses-d0020_desc-brain_mask.nii.gz
        ├── sub-OAS30204_ses-d0020_desc-preproc_T1w.json
        ├── sub-OAS30204_ses-d0020_desc-preproc_T1w.nii.gz
        ├── sub-OAS30204_ses-d0020_dseg.nii.gz
        ├── sub-OAS30204_ses-d0020_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
        ├── sub-OAS30204_ses-d0020_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
        ├── sub-OAS30204_ses-d0020_label-CSF_probseg.nii.gz
        ├── sub-OAS30204_ses-d0020_label-GM_probseg.nii.gz
        ├── sub-OAS30204_ses-d0020_label-WM_probseg.nii.gz
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_desc-brain_mask.json
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_desc-brain_mask.nii.gz
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_desc-preproc_T1w.json
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_desc-preproc_T1w.nii.gz
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_dseg.nii.gz
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_label-CSF_probseg.nii.gz
        ├── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_label-GM_probseg.nii.gz
        └── sub-OAS30204_ses-d0020_space-MNI152NLin2009cAsym_label-WM_probseg.nii.gz


"""

**Comment by ali3654** [comment]
hello @oesteban,

there is no option that outputs only the normalized nifiti files ? 
Because actually i only need the normalized nifti files.

**Comment by oesteban** [comment]
Not at the moment. I think you can always set the output folder to be in `/tmp` or some other fast, transient storage and then have a final hook that copies only the files you really want to the final location.

However, the only upshot to this is saving storage. Any other aspect of the solution would count as a downside.

Instead, I'd mirror all fMRIPrep outputs to some cold, cheap storage location and cleanup the files you don't need on your workstation.

I don't think there are plans to add granular control over the outputs (or more granular it is now), and the argument to consider it must be really strong.

**Comment by ali3654** [comment]
ok then I know about it, thank you  👍
