### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'mri_convert'

### ISSUE THREAD

**Issue by Meryam1985** [nipreps/smriprep#244]
IHello
 got the error:
File "/home/besma/.local/bin/smriprep", line 8, in <module>
    sys.exit(main())
  File "/home/besma/.local/lib/python3.8/site-packages/smriprep/cli/run.py", line 10, in main
    return build_opts(opts)
  File "/home/besma/.local/lib/python3.8/site-packages/smriprep/cli/run.py", line 182, in build_opts
    if not check_valid_fs_license():
  File "/home/besma/.local/lib/python3.8/site-packages/niworkflows/utils/misc.py", line 312, in check_valid_fs_license
    proc = sp.run(_cmd, stdout=sp.PIPE, stderr=sp.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mri_convert'

FileNotFoundError: [Errno 2] No such file or directory: 'mri_convert'

**Are you positive that the input dataset is BIDS-compliant?**
- [ *] I have used the online BIDS-Validator
- [ ] I have run a local installation of the BIDS-Validator (please, note the version of the validator here).
- [ ] I let *sMRIPrep* check it for me (in other words, **I didn't set the `--skip-bids-validation` argument**).
- [ ] No, I haven't checked myself AND used the `--skip-bids-validation` argument.

***sMRIPrep* feedback information**
Please attach the full log written to the standard output and the crashfile(s), if generated.

**Visual reports of *sMRIPrep***
If applicable, add screenshots or attach the corresponding "reportlets" to help explain your problem.

**Installation type (please complete the following information):**
 - [ * ] "Bare-metal"
 - [ ] Singularity
 - [ ] Docker

**Additional context**

**Comment by oesteban** [comment]
Please reopen if the answer above did not resolve the issue.

**Comment by Meryam1985** [comment]
HELLO
Today I'm trying to run smriprep from docker. I got this error""'ERROR: a valid license file is required for FreeSurfer to run. '
RuntimeError: ERROR: a valid license file is required for FreeSurfer to run. sMRIPrep looked for an existing license file at several paths, in this order: 1) command line argument ``--fs-license-file``; 2) ``$FS_LICENSE`` environment variable; and 3) the ``$FREESURFER_HOME/license.txt`` path. Get it (for free) by registering at https://surfer.nmr.mgh.harvard.edu/registration.html
"""
despite that, I am already registered in FREE Surfer and I gave the license file path smriprep-docker --fs-license-file Home / Downloads / license.txt /
I work under ubunto.

**Comment by oesteban** [comment]
Please copy and paste the exact command line you are running. Thanks

**Comment by Meryam1985** [comment]
Thank you very much for answering me
here is the command
smriprep-docker --fs-license-file Home / Downloads / license.txt / / Home / Desktop / test / sub-3416820 / / Home / Desktop / test / b / participant

**Comment by Meryam1985** [comment]
can you explain to me how to allow docker to access the Downloads directory ... maybe the problem is there.

**Comment by mgxd** [comment]
@Meryam1985 can you move your license to `/ Home / Desktop / license.txt` and retry?

**Comment by Meryam1985** [comment]
I try....I have the same error.

**Comment by effigies** [comment]
I'm assuming you're not actually having the spaces in the command? Also, if this needs further discussion, please open another issue rather than commenting in a closed issue. Otherwise it's likely to fall through the cracks.
