### ISSUE TITLE
Support for rhesus macaque preprocessing?

### ISSUE THREAD

**Issue by anthonycrane** [nipreps/smriprep#25]
Hello, I am hoping to use fmriprep for preprocessing data from rhesus monkeys, but I'm not sure if the pipeline is set up for this quite yet. If not, I'd love to contribute to the project! Is there anything on the horizon for supporting preprocessing imaging data from different species?

**Comment by oesteban** [comment]
With the advance of NiRodents and NiBabies I  think this particular issue would fall in a midpoint of generalization. As the main holdback is the addition of proper templates to templateflow, I'll close this issue and maybe reopen when the templates are up and the workflow still does not work for macaques.
