### ISSUE TITLE
Wrong probseg fmriprep output from freesurfer pipeline

### ISSUE THREAD

**Issue by julfou81** [nipreps/smriprep#254]
Hi, I noticed that the output of the segmentation from the freesurfer pipeline vs the FLIRT pipeline produced different probseg files. Especially, the probseg files from Freesurfer pipeline stream are binarized and not looking nice at all.
probseg-GM produced through Freesurfer pipeline:
![T1w_probseg_GM_FS](https://user-images.githubusercontent.com/32452352/111701344-fc75ee80-883a-11eb-97d6-a9a899e149e7.png)

probseg-GM produced through FSL  pipeline:
![T1w_probseg_GM_FSL](https://user-images.githubusercontent.com/32452352/111701444-262f1580-883b-11eb-9130-cceed15e8614.png)

probseg-GM + WM with Freesurfer pipeline:
![T1w_probseg_GM+WM_FS](https://user-images.githubusercontent.com/32452352/111701527-45c63e00-883b-11eb-877a-05dd4fbf5b9c.png)

probseg-GM + WM with FSL pipeline:
![T1w_probseg_GM+WM_FSL](https://user-images.githubusercontent.com/32452352/111701574-54acf080-883b-11eb-8fe2-b7b1ac184348.png)

probseg-WM with FS pipeline:
![T1w_probseg_WM_FS](https://user-images.githubusercontent.com/32452352/111702355-6fcc3000-883c-11eb-8263-04020d58155a.png)

wm.mgz file in the freesurfer folder: it looks ok!
![T1w_probseg_wmMGZ_freesurfer](https://user-images.githubusercontent.com/32452352/111702461-938f7600-883c-11eb-9f23-5fd5d0f3d4c5.png)

Has anybody also noticed this on its data?

 

### What version of fMRIPrep are you using?
20.2.0
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity
### What is the exact command-line you used?
```
</usr/local/miniconda/bin/fmriprep /work/EcritApp /work/EcritApp/derivatives --fs-license-file /work/freesurfer/license.txt participant --participant_label 001 --fd-spike-threshold 0.9 --return-all-components -w /work/temp_data_EcritApp --omp-nthreads 8 --nthreads 12 --mem_mb 40000 --ignore slicetiming --output-spaces T1w MNI152NLin2009cAsym MNIPediatricAsym:cohort-3>
```

### Have you checked that your inputs are BIDS valid?
Yes
### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
<No errors to report!>
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?

Yes Freesurfer results were re-used

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

**Comment by oesteban** [comment]
Okay, I'm assigning this to the upcoming new release, as new TPMs will drastically affect the results of aCompCor.

**Comment by ahoopes** [comment]
There's no direct way to generate gm/wm/csf tissue probabilities in FS, but you could add the `-write_probs <filename>` flag to `mri_ca_label` via the recon-all expert options. This saves the aseg posteriors, then you could do some post-processing on that to generate the tissue maps.

**Comment by effigies** [comment]
These are the histograms of the posteriors. Unclear how to get a tissue probability map from these. @ahoopes a little guidance would be appreciated.

![calabel_posterior0](https://user-images.githubusercontent.com/83442/131255678-b6d02a2c-85b5-4d54-b760-dea0b87e4acb.png)
![calabel_posterior1](https://user-images.githubusercontent.com/83442/131255679-e08dd73e-b2f2-423b-9662-c6f0ef2e8358.png)
![calabel_posterior2](https://user-images.githubusercontent.com/83442/131255680-77bd183a-3159-469c-b440-ad825306ddac.png)

@oesteban Is there any reason not to revert to FAST for TPMs until this is resolved?

**Comment by mgxd** [comment]
> Is there any reason not to revert to FAST for TPMs until this is resolved?

Good point, may be the easiest solution for now..

**Comment by oesteban** [comment]
The only reason is to minimize the use of commercially restricted FSL. But in the short term, it might actually be a decent solution.

An alternative to post-processing these posteriors and avoiding FSL (while being an acceptable solution with `--fs-no-reconall`) would be to use ATROPOS instead, and feed it with priors generated from either aseg (roughly what we already have, converting from aseg to 3-tissue segmentation) or from a template (for the `--fs-no-reconall` pathway). @eilidhmacnicol is probably the best resource here as she has played quite a bit with ATROPOS' priors (although she's off right this minute, will be back next week).

**Comment by effigies** [comment]
Sounds good. Then, in order not to block a 21.0.0 release, we will revert to FAST for now. Let's make an issue to further explore FreeSurfer/ANTs replacements for 21.1.

**Comment by ahoopes** [comment]
> These are the histograms of the posteriors. Unclear how to get a tissue probability map from these.

Just looked at the code a bit. It's kind of a hidden feature, so there's no much (or any) documentation. The `-write_probs` flag saves a volume that includes only the top 3 label probabilities for each voxel. So, it's a 6-frame image where each frame represents (label-1, prob-1, label-2, prob-2, label-3, prob-3).
