### ISSUE TITLE
adding surface based morphometry outputs (cortical thickness, sulcal depth, folding curvature) to CIFTI-output

### ISSUE THREAD

**Issue by ericfeczko** [nipreps/smriprep#288]
**Is your feature request related to a problem? Please describe.**
Much of the neuroimaging community from infant neuroimaging to adults wants to measure surface based morphometrics and use cortical thickness/folding curvature/sulcal depth. However, the CIFTI options do not allow for the output of these metrics into derivatives.

**Describe the solution you'd like**
I would like cortical thickness/folding curvature/sulcal depth derived from the freesurfer component to be carried over to the final derivatives.

**Describe alternatives you've considered**
None.

**Additional context**
This is additionally critical for ensuring proper projection of BOLD data to cortical surfaces -- and would help eliminate aliasing issues identified by Guarav's group.

**Comment by tsalo** [comment]
Did #325 address this?

**Comment by effigies** [comment]
Yes.
