### ISSUE TITLE
Can smriprep be used to create a custom template?

### ISSUE THREAD

**Issue by dkp** [nipreps/smriprep#324]
I am confused by documentation on the smriprep site that says the T1w images are aligned and averaged.  Is this only within a subject with multiple T1w images or is it an average across subjects that could subsequently be used to build a custom template?

Thanks in advance for your clarification.

**Comment by effigies** [comment]
This is within subject. I don't have any guidance for making a study specific template. It's possible smriprep outputs could be useful there, but I really don't know.

**Comment by dkp** [comment]
Thanks for the explanation
