### ISSUE TITLE
Docker pushes fail on tags

### ISSUE THREAD

**Issue by effigies** [nipreps/smriprep#330]
Example: https://app.circleci.com/pipelines/github/nipreps/smriprep/678/workflows/efef46c8-1cfc-4448-9afe-438e3cebc733/jobs/3269

```Shell
#!/bin/bash -eo pipefail
docker tag nipreps/smriprep nipreps/smriprep:${CIRCLE_BRANCH#docker/}
docker push nipreps/smriprep:${CIRCLE_BRANCH#docker/}
```

```console
Error parsing reference: "nipreps/smriprep:" is not a valid repository/tag: invalid reference format
Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by mgxd** [comment]
We should probably use the following heuristic:
1) check for CIRCLE_TAG
1) if none, check if CIRCLE_BRANCH has the `docker/` prefix
