### ISSUE TITLE
WRAPPER: docker unable to find image of version 0.11.0

### ISSUE THREAD

**Issue by Kellsens** [nipreps/smriprep#342]
Hi all, I'm trying to run the wrapper smriprep-docker and I'm getting the folowing error
```
Downloading. This may take a while...
Unable to find image 'nipreps/smriprep:0.11.0' locally
docker: Error response from daemon: manifest for nipreps/smriprep:0.11.0 not found: manifest unknown: manifest unknown.
```
I've checked at the HUB Docker for smriprep and noted that there is not a image for 0.11.0. There is the latest (of course) but I'm afraid that the wrapper points directly to the version image.
Also I've tried to install manually using

`docker pull nipreps/smriprep:0.11.0`

which throws a error of image not found. Then I tried using

`docker pull nipreps/smriprep:latest`

that downloads everything, but doesn't fix the problem mentioned above.

I've tried to find some mention about this situation here and I couldn't find it. Can you guys help me with that?
Thank you.

**Comment by effigies** [comment]
Hmm. Looks like the last couple releases didn't get pushed to DockerHub. But you could try `nipreps/smriprep:unstable`. `smriprep-docker -i nipreps/smriprep:unstable` should work.

**Comment by Kellsens** [comment]
Thank you a lot @effigies . It worked perfectly.
