### ISSUE TITLE
Built-in Local Gyrification Index (LGI) Flag

### ISSUE THREAD

**Issue by margokersey** [nipreps/smriprep#352]
Hi there,

Is it possible for LGI calculation to be built into the pipeline? When running FreeSurfer recon-all, I usually add the -localGI flag which generates lh.pial_lgi and rh.pial_lgi. Apologies if this is already integrated with smriprep- I may have missed something in the documentation.

Thank you so much!

**Comment by effigies** [comment]
Sorry, I missed this. It's pretty easy to post-run `recon-all -localGI` on a FreeSurfer directory before or after running fmriprep/smriprep. We try to keep the number of options as small as possible, and that this is easy to do outside smriprep makes me reluctant to add it.
