### ISSUE TITLE
msmall registration seems off

### ISSUE THREAD

**Issue by Shotgunosine** [nipreps/smriprep#374]
**Describe the bug**
I ran a dataset through both fmriprep-msmall and [Connor Liston's group's HCP based multi-echo pipeline](https://github.com/Shotgunosine/Liston-Laboratory-MultiEchofMRI-Pipeline/tree/edb_template). I've got ROIs for the dorsolateral prefrontal cortex (DLPFC) and subgenual cortex (SGC) in FSLR space. I compared the location of those ROIs on the following mid-thickness surface meshes:
  Top Left: Mesh transformed the the project-unproject sphere. 
  Top Right: Templateflow's FSLR Mesh
  Bottom Left: The mesh tranformed by the msmall sphere
  Bottom Right: The FSLR Mesh from the Liston pipeline
![Screenshot 2023-10-03 at 2 39 51 PM](https://github.com/nipreps/smriprep/assets/5289368/71fc357e-2d14-4059-a74c-790c985bfe61)

The msmall ROIs seem off (DLPFC too anterior, SGC, a little bit too posterior) compared to the others.

This is just sub-24563 from https://openneuro.org/datasets/ds004787, but the rest of the subjects there have similar issues. 

**Exact command line executed**
```Shell
singularity run ${ROOTDIR}/code/fmriprep_msmsulc.simg ${ROOTDIR}/BIDS \${TMPDIR}/${s##*sub-}.out participant --participant_label ${s##*sub-} -w \${TMPDIR}/${s##*sub-}.wrk \
--notrack --output-space MNI152NLin6Asym:res-2 T1w fsaverage fsLR fsnative \
--nthreads \${SLURM_CPUS_PER_TASK} --omp-nthreads \${SLURM_CPUS_PER_TASK} \
--me-output-echos --cifti-output 91k --mem 36 \
--skip_bids_validation --fs-license ${license} --project-goodvoxels; \
        rsync -a --chown=:EDB \${TMPDIR}/${s##*sub-}.out/ ${ROOTDIR}/derivatives/fmriprep-msmsulc/ ; \
        rsync -a --chown=:EDB \${TMPDIR}/${s##*sub-}.wrk ${ROOTDIR}/work/fmriprep-msmsulc/ ; \
```

The msmall mesh comes from `24563.wrk/fmriprep_23_2_wf/single_subject_24563_wf/func_preproc_ses_1_task_rest_acq_MBME_run_1_echo_1_wf/bold_fsLR_resampling_wf/_hemi_L/downsampled_midthickness/lh.midthickness_converted_resampled.surf.gii`   
generated by:  
```Shell
wb_command -surface-resample /lscratch/8536404/24563.wrk/fmriprep_23_2_wf/single_subject_24563_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/fix_surfs/mapflow/_fix_surfs6/lh.midthickness_converted.gii /lscratch/8536404/24563.wrk/fmriprep_23_2_wf/single_subject_24563_wf/anat_preproc_wf/sphere_reg_wf/msm_sulc_wf/msmsulc/mapflow/_msmsulc0/lh.sphere.reg.surf.gii /home/zugmana2/.cache/templateflow/tpl-fsLR/tpl-fsLR_hemi-L_den-32k_sphere.surf.gii BARYCENTRIC lh.midthickness_converted_resampled.surf.gii
```

The project-unproject mesh was generated with:
```Shell
wb_command -surface-resample /data/EDB/TMSpilot/work/fmriprep-23-1-3/24563.wrk/fmriprep_23_2_wf/single_subject_24563_wf/anat_preproc_wf/surface_recon_wf/gifti_surface_wf/fix_surfs/mapflow/_fix_surfs6/lh.midthickness_converted.gii /data/EDB/TMSpilot/work/fmriprep-23-1-3/24563.wrk/fmriprep_23_2_wf/single_subject_24563_wf/anat_preproc_wf/sphere_reg_wf/project_unproject/mapflow/_project_unproject0/lh.sphere.reg_converted_unprojected.surf.gii /home/nielsond/.cache/templateflow/tpl-fsLR/tpl-fsLR_hemi-L_den-32k_sphere.surf.gii BARYCENTRIC lh.midthickness_converted_resampled_notmsmsulc.surf.gii
```

**Are you positive that the input dataset is BIDS-compliant?**
- [ ] I have used the online BIDS-Validator
- [ ] I have run a local installation of the BIDS-Validator (please, note the version of the validator here).
- [ ] I let *sMRIPrep* check it for me (in other words, **I didn't set the `--skip-bids-validation` argument**).
- [X] No, I haven't checked myself AND used the `--skip-bids-validation` argument.
There were some BIDS issues on the version of the dataset I ran this on, but none that should have impacted the anatomical.

**Installation type (please complete the following information):**
 - [ ] "Bare-metal"
 - [ X] Singularity
 - [ ] Docker

**Additional context**
Here's the fmriprep version from the singularity container:
```Shell
(base) [nielsond@cn2878 code]$ singularity run fmriprep_msmsulc.simg --version
fMRIPrep v23.2.0.dev36+g603ce440
```

I'm rerunning fMRIPrep and the Liston pipeline on the defaced data that I shared on OpenNeuro so that I can post those outputs as well.

**Comment by effigies** [comment]
Should be resolved. Please reopen if you run into this again.
