### ISSUE TITLE
Move to ruff?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipreps/smriprep#395]
**Is your feature request related to a problem? Please describe.**

Move from multiple to a single all-in-one linter.

**Describe the solution you'd like**

All current linters can be replaced by [ruff](https://astral.sh/ruff):
* black
* flake8
* isort

An additional linter could be added in the process:
* pyupgrade

**Describe alternatives you've considered**

Keep as is.

**Comment by effigies** [comment]
Yes, I actually have a branch where I'm doing that.

**Comment by DimitriPapadopoulos** [comment]
Ah, great. Would you be agree to add pyupgrade rules ("UP")?

#396 fixes the last pyugrade issue in the current sources.

**Comment by effigies** [comment]
Yup, that was the plan.
