### ISSUE TITLE
T1w images incorrectly detected as skull-stripped (difference between 0.12.2 -> 0.13.1)

### ISSUE THREAD

**Issue by psadil** [nipreps/smriprep#401]
**Describe the bug**

I have T1w images like the following that are being detected as having had their skulls already stripped

![image](https://github.com/nipreps/smriprep/assets/8172767/a37583fa-faa5-4a9d-bebe-cfc8a45f38f1)

With 0.12.2, the skulls were detected as needing to be stripped.

**Exact command line executed**
```Shell
$ singularity build smriprep_0.13.1.sif docker://nipreps/smriprep:0.13.1
$ singularity run -e --bind ${root}:/ds --bind ${scratch}:/scratch code/smriprep_0.13.1.sif --nprocs 16 --omp-nthreads 8 --mem-gb 24 --output-spaces T1w MNI152NLin2009cAsym MNI152NLin6Asym --fs-license-file /ds/smriprep/code/license -w /scratch/work --participant-label AAO1062 --no-submm-recon /ds/bids/rawdata /ds/smriprep/derivatives participant
```

**Are you positive that the input dataset is BIDS-compliant?**
- [ ] I have used the online BIDS-Validator
- [ ] I have run a local installation of the BIDS-Validator (please, note the version of the validator here).
- [x] I let *sMRIPrep* check it for me (in other words, **I didn't set the `--skip-bids-validation` argument**).
- [ ] No, I haven't checked myself AND used the `--skip-bids-validation` argument.

***sMRIPrep* feedback information**
Please attach the full log written to the standard output and the crashfile(s), if generated.

```
231128-18:11:30,567 nipype.workflow Level 25:
	 
    Running sMRIPrep version 0.13.1:
      * BIDS dataset path: /ds/bids/rawdata.
      * Participant list: ['AAO1062'].
      * Run identifier: 20231128-181104_1efc0d9c-4437-4a93-8ebe-27a4f3bd9a0e.

    Spatial References: T1w, MNI152NLin2009cAsym:res-native, MNI152NLin6Asym:res-native
    
231128-18:11:31,929 nipype.workflow INFO:
	 ANAT Stage 1: Adding template workflow
231128-18:11:34,226 nipype.workflow INFO:
	 ANAT Stage 2: Preparing brain extraction workflow
231128-18:11:35,37 nipype.workflow INFO:
	 ANAT Stage 2: Skipping skull-strip, INU-correction only
231128-18:11:35,59 nipype.workflow INFO:

```

[full log](https://github.com/nipreps/smriprep/files/13494553/smriprep_0.log) (note that this run crashed due to what I believe to be an unrelated reason)

**Visual reports of *sMRIPrep***
If applicable, add screenshots or attach the corresponding "reportlets" to help explain your problem.

**Installation type (please complete the following information):**
 - [ ] "Bare-metal"
 - [x] Singularity
 - [ ] Docker

**Additional context**

https://github.com/nipreps/smriprep/blob/e460f6d04336bccc365b212f4083c4d6fd3be6e9/smriprep/workflows/anatomical.py#L798 

ends up evaluating to `False`

**Comment by effigies** [comment]
TBH I thought this check was so bad nobody used it, but it turns out it's default on smriprep.

Looks like it should be `run_skull_strip = not all(...)`. Thanks for catching this. Care to open a PR?
