### ISSUE TITLE
Handle IsRunning files in recon-all

### ISSUE THREAD

**Issue by effigies** [nipreps/smriprep#41]
recon-all creates `IsRunning` files to indicate that it is currently running, and blocks other instances of recon-all from running. Some crashes aren't recovered from gracefully enough for recon-all to remove the file, resulting in a need to manually remove the file.

We have a few options:

1) Leave it to the user to remove; `recon-all` gives a reasonably thorough error message
2) Always remove; assume that nobody will ever run two instances of fmriprep on the same subject
3) Sometimes remove, based on a flag that indicates the user knows what they're doing?

I'm open to suggestions. I'm a little inclined to 1 or 3.

**Comment by oesteban** [comment]
Bumping this up. I think that option 3 + checking the mtime of the `recon-all.log` gives us the best tradeoff. If mtime < 24h then the warning when deleting IsRunning files is noisier and warns about the risks of running competing fmriprep processes.
