### ISSUE TITLE
Write out fsnative surface files registered to fsLR space

### ISSUE THREAD

**Issue by tsalo** [nipreps/smriprep#447]
**Is your feature request related to a problem? Please describe.**

My understanding is that the resulting surface files will have the same vertices and mesh as the standard-space (dhcpAsym or fsLR) surface, but will retain the subject's fsnative geometry. This way users can visualize standard-space surface maps on the subject's unique topology (sulci, gyri, etc.), as is recommended in [Jeganathan et al. (preprint)](https://doi.org/10.1101/2024.07.09.602799).

**Describe the solution you'd like**

sMRIPrep would output pial, white matter, midthickness, inflated, and very-inflated surface files with `space-fsLR`.

**Describe alternatives you've considered**

Currently, XCP-D performs this step, but I'm pretty sure the nipreps team and DCAN lab have discussed it and wanted to move it into sMRIPrep/fMRIPrep/Nibabies.

**Additional context**

This is a duplicate of https://github.com/nipreps/nibabies/issues/367.

**Comment by tsalo** [comment]
XCP-D's workflow includes the following steps:

1. Split up the anatomical-to-template transform (any volumetric template is fine) from fMRIPrep into affine and warpfield components.
2. Convert the affine transform into a world transform format.
3. Convert the warpfield transform into FNIRT format. The same is done for the warpfield component of the template-to-anatomical transform as well.
4. Convert the sphere.reg file to GIFTI format.
5. Project the `sphere_reg` file to fsLR to get a `sphere_reg_fsLR` file.
6. Resample the pial and white matter surfaces to fsLR-32k.
7. Apply the world-format affine to the pial and white matter surfaces.
8. Apply the FNIRT-format warpfield to the pial and white matter surfaces.
9. Generate new midthickness, inflated, and very-inflated surfaces from the fsLR-space pial and white matter files.

I don't think steps 1-3 or 7-8 are necessary for sMRIPrep. My understanding is that XCP-D only does this so the surfaces can be overlaid on top of the volumetric anatomical outputs that have been warped to the chosen template. XCP-D should be able to do the same thing after the rest of the steps.

sMRIPrep already does steps 4 and 5, and it seems to apply step 6 only to the midthickness files in `init_resample_midthickness_wf`. I think we just need to make `init_resample_midthickness_wf` more general to apply the same step to the pial, white matter, inflated, and very-inflated files.

**Comment by effigies** [comment]
I'm +1 on this. I can't see a really good reason not to apart from that we need to decide a naming convention. BEP011 is silent on this, so we should probably eventually propose it to BIDS.

I guess:

```
sub-X_hemi-<hemisphere>_space-<mesh>_den-<density>_<pial|midthickness|white|etc>.surf.gii
```

I think this would be consistent with using `space-fsLR` for `sphere.reg`.

**Comment by tsalo** [comment]
No it's the subject's, but created using the HCP pipeline's approach (vs... I think Freesurfer's approach?).

**Comment by effigies** [comment]
Got it.

**Comment by zhitao-guo** [comment]
Hi Chris, I hope you're doing well. 

I’ve encountered a strange issue where fMRIPrep 24.1.1 and 24.0.1 on my system are unable to output the native fsLR 32k mesh files, although it works fine for others. Could you kindly help me interpret what might be causing this problem? And here is a link to more detailed information: https://github.com/PennLINC/xcp_d/issues/1305

Thanks a lot!

**Comment by effigies** [comment]
This is an open issue and still needs to be implemented. I'm not sure what others are doing to retrieve these files. They exist in the working directory, but fMRIPrep does not emit them.

**Comment by effigies** [comment]
No.

**Comment by effigies** [comment]
Apologies for the brevity, was in a meeting. This still needs to be done. I think you're right that only the midthickness is resampled, since only that is used as an intermediate derivative.
